### ISSUE TITLE
Use `CARGO_REGISTRY_TOKEN` instead of `CARGO_API_KEY`

### ISSUE THREAD

**Issue by marcoieni** [rust-github/template#28]
Environment variable `CARGO_REGISTRY_TOKEN` is suggested for CI. Check if you can use it instead of `CARGO_API_KEY`.
docs [here](https://doc.rust-lang.org/cargo/reference/config.html?highlight=CARGO_REGISTRY_TOKEN#credentials)

You can probably remove this line after:
https://github.com/rust-github/template/blob/44d7942c4f3348e9e6ab9d5239b332c57bcbd718/template/.github/workflows/cd.yml#L121

Also update the website docs.

**Comment by RishiKumarRay** [comment]
Do we have to go for CI?

**Comment by marcoieni** [comment]
I am not sure what you mean, but we automatically invoke cargo publish on every tag here:
https://github.com/rust-github/template/blob/44d7942c4f3348e9e6ab9d5239b332c57bcbd718/template/.github/workflows/cd.yml#L106-L121

This command needs to know the API key.

**Comment by marcoieni** [comment]
updated website in https://github.com/rust-github/rust-github.github.io/commit/277d24070731bf69bf9b82589085e707b3dee981

template updated in https://github.com/rust-github/template/commit/c3ded20ac7d6a3501e494bcdae865b0bc650f15f
