### ISSUE TITLE
Failed to parse string when running job[Coveralls]

### ISSUE THREAD

**Issue by pplmx** [rust-github/template#35]
```text
Run coverallsapp/github-action@master
  with:
    github-token: ***
    path-to-lcov: ./lcov.info
    coveralls-endpoint: https://coveralls.io
  env:
    CACHE_ON_FAILURE: false
    CARGO_INCREMENTAL: 0
Using lcov file: ./lcov.info
Error:  "[2](https://github.com/pplmx/ip-tools/runs/7628225107?check_suite_focus=true#step:6:2)022-08-02T09:11:[3](https://github.com/pplmx/ip-tools/runs/7628225107?check_suite_focus=true#step:6:3)3.[7](https://github.com/pplmx/ip-tools/runs/7628225107?check_suite_focus=true#step:6:7)7[8](https://github.com/pplmx/ip-tools/runs/7628225107?check_suite_focus=true#step:6:8)Z"  'error from lcovParse: ' 'Failed to parse string'
Error:  "2022-08-02T0[9](https://github.com/pplmx/ip-tools/runs/7628225107?check_suite_focus=true#step:6:10):11:33.779Z"  'input: ' ''
Error:  "2022-08-02T09:[11](https://github.com/pplmx/ip-tools/runs/7628225107?check_suite_focus=true#step:6:12):33.779Z"  'error from convertLcovToCoveralls'
Error: Failed to parse string
```

**Comment by marcoieni** [comment]
Thank you for reporting. Can you link or copy paste the yaml so that I can see the CI pipeline and try to reproduce the issue? :)

**Comment by pplmx** [comment]
Hi, @MarcoIeni 

I don't change it, which is from the template. 
FYI. Here is my ci.yml
https://github.com/pplmx/ip-tools/blob/main/.github/workflows/ci.yml

**Comment by marcoieni** [comment]
Hey sorry if this is taking a lot but I'm busy in these days :(

**Comment by Ran-oops** [comment]
Oh that’s okay. :) Take your time freely.

**Comment by pplmx** [comment]
Oh that's okay. Take your time freely.

**Comment by marcoieni** [comment]
Hey pplmx, I tried to reproduce this issue in our minimal example, so I pushed a new commit [here](https://github.com/MarcoIeni/rust-gh-example/commit/37fa784dbb74dd24dc761b13d102acf0a1f6cd21).
However, the coverage was working as expected 🤔 

![image](https://user-images.githubusercontent.com/11428655/184915762-00ca15b5-3cf2-4b4e-a151-970129f14133.png)

Your issue might be a problem with one of these projects:
- https://github.com/actions-rs/tarpaulin
- https://github.com/xd009642/tarpaulin
- https://github.com/coverallsapp/github-action

As a side note, I need to investigate if our approach is still the best way to calculate rust code coverage 🤔

**Comment by pplmx** [comment]
Yep, the first two commits worked well. Since the 3rd commit, the action ran in failure. 
Here is my 3rd commit content. I don't think this commit will affect the result of action, or Maybe?
https://github.com/pplmx/ip-tools/commit/e0c9f9e0cbc1e2707cf7f2440999f831beaefa45

**Comment by pplmx** [comment]
FYI. Screenshot for Github Action.
![image](https://user-images.githubusercontent.com/26994103/185021328-5704f625-2a80-48cf-a1c2-48d3fcef46be.png)

**Comment by marcoieni** [comment]
Maybe there are some issues with the configuration in the Cargo.toml file you added. I don't know 😕

**Comment by marcoieni** [comment]
I removed code coverage as it is today, because it's not working [anymore](https://github.com/rust-github/rust-gh-example/commit/ae22f05a8360e2fbd2d89062feaf0792fa2ad829).
