### ISSUE TITLE
why is this template file so strange?

### ISSUE THREAD

**Issue by pplmx** [rust-github/template#37]
Hi, @MarcoIeni 
What is the syntax for this?
Any documentation for it?
Thanks a lot.

![image](https://user-images.githubusercontent.com/26994103/189158019-a165f142-36fa-4aee-9ef9-93ca63378904.png)

**Comment by marcoieni** [comment]
Hi Mystic!

It's documented here: https://github.com/rust-github/template/blob/main/CONTRIBUTING.md

**Comment by pplmx** [comment]
okay, Thanks Marco :)
