### ISSUE TITLE
Template of .github/workflows/cd.yml did not render.

### ISSUE THREAD

**Issue by CodeMan99** [rust-github/template#50]
## Executed

```shell
$ cargo generate --bin --name example rust-github/template
 Favorite `rust-github/template` not found in config, using it as a git repository: https://github.com/rust-github/template.git
 Destination: /home/vscode/example ...
 project-name: example ...
 Generating template ...
 GitHub username (or organization): CodeMan99
 Project description: Example
 Moving generated files into: `/home/vscode/example`...
 Initializing a fresh Git repository
 Done! New project created /home/vscode/example
```

## Problem

The https://github.com/rust-github/template/blob/main/template/.github/workflows/cd.yml file appears as-is without any interpolation of values.

### `HEAD`

This repository is 1af92aba786991e28d1c382bcb5f9e2a1623905c.

### `cargo-generate --version`

I install version `0.18.5` via `cargo install --locked cargo-generate`.

**Comment by marcoieni** [comment]
Yeah, I'm sorry, this has been on my todo list forever. If anyone has time to debug this, PR is welcome!
